micronaut:
  application:
    name: bank
  router:
    static-resources:
      swagger:
        paths:
          - classpath:META-INF/swagger
          - classpath:swagger
        mapping: /swagger/**

datasources:
  default:
    url: ${JDBC_URL:`jdbc:h2:mem:default;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;LOCK_MODE=3`}
    username: ${JDBC_USER:sa}
    password: ${JDBC_PASSWORD:""}
    driverClassName: ${JDBC_DRIVER:org.h2.Driver}
    maximumPoolSize: 15
    minimumIdle: 5

jpa:
  default:
    packages-to-scan:
      - 'com.dodo.bank.account'
      - 'com.dodo.bank.transfer'
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true

jackson:
  serialization:
    writeDatesAsTimestamps: false
